### ISSUE TITLE
import statement throws `SyntaxError`

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ava#108]
When running the `pageres` tests, this is the error thrown.

```
/Users/sam/Projects/opensource/pageres/test/serverForCookieTests.js:1
(function (exports, require, module, __filename, __dirname) { import http from 'http';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at require.extensions..js (/Users/sam/Projects/opensource/pageres/node_modules/nyc/index.js:103:12)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/sam/Projects/opensource/pageres/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/sam/Projects/opensource/pageres/test/test.js:10:30)
    at Module._compile (module.js:434:26)
    at normalLoader (/Users/sam/Projects/opensource/pageres/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/sam/Projects/opensource/pageres/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/sam/Projects/opensource/pageres/node_modules/ava/lib/babel.js:26:1)
    at Module._compile (module.js:434:26)
    at Object.require.extensions..js (/Users/sam/Projects/opensource/pageres/node_modules/nyc/index.js:103:12)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at Function.runMain (/Users/sam/.node-spawn-wrap-71353-300a1eba5683/node:40:10)
    at Object.<anonymous> (/Users/sam/Projects/opensource/pageres/node_modules/nyc/bin/nyc.js:15:6)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at Object.<anonymous> (/Users/sam/.node-spawn-wrap-71353-300a1eba5683/node:140:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
TypeError: Cannot read property 'stack' of undefined
    at error (/Users/sam/Projects/opensource/pageres/node_modules/ava/cli.js:50:19)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
From previous event:
    at Object.<anonymous> (/Users/sam/Projects/opensource/pageres/node_modules/ava/cli.js:206:34)
    at Module._compile (module.js:434:26)
    at Object.require.extensions..js (/Users/sam/Projects/opensource/pageres/node_modules/nyc/index.js:103:12)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at Function.runMain (/Users/sam/.node-spawn-wrap-71353-300a1eba5683/node:40:10)
    at Object.<anonymous> (/Users/sam/Projects/opensource/pageres/node_modules/nyc/bin/nyc.js:15:6)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at Object.<anonymous> (/Users/sam/.node-spawn-wrap-71353-300a1eba5683/node:140:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
npm ERR! Test failed.  See above for more details.
```

**Comment by sindresorhus** [comment]
That's because AVA no longer transpiles required files. That was a nasty bug. It's already fixed in Pageres. Just pull down latest master.

**Comment by SamVerschueren** [comment]
Good to know! Thanks :+1:

**Comment by Qix-** [comment]
Usually "reserved keyword" error messages are a sign either a library is outdated or your node installation is outdated. :+1:
