### ISSUE TITLE
resolving to a different Babel version

### ISSUE THREAD

**Issue by TrySound** [sindresorhus/ava#129]
```js
import test from 'ava';

test('name', t => {
	t.pass();
	t.end();
});

```

```
C:\Users\Frontend\AppData\Roaming\nvm\v0.12.5\node_modules\ava\node_modules\babel-core\lib\transformation\plugin.js:121
      throw new TypeError(messages.get("pluginNotFile", this.key));
            ^
TypeError: Plugin "babel-plugin-espower" is resolving to a different Babel version than what is performing the transform
ation.
    at Plugin.buildPass (C:\Users\Frontend\AppData\Roaming\nvm\v0.12.5\node_modules\ava\node_modules\babel-core\lib\tran
sformation\plugin.js:121:13)
    at PluginManager.add (D:\Workflow\sandbox\aa\node_modules\babel-core\lib\transformation\file\plugin-manager.js:216:5
5)
    at File.buildTransformers (D:\Workflow\sandbox\aa\node_modules\babel-core\lib\transformation\file\index.js:237:21)
    at new File (D:\Workflow\sandbox\aa\node_modules\babel-core\lib\transformation\file\index.js:139:10)
    at Pipeline.transform (D:\Workflow\sandbox\aa\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at Object.transformFileSync (D:\Workflow\sandbox\aa\node_modules\babel-core\lib\api\node.js:137:37)
    at compile (D:\Workflow\sandbox\aa\node_modules\babel-core\lib\api\register\node.js:132:20)
    at normalLoader (D:\Workflow\sandbox\aa\node_modules\babel-core\lib\api\register\node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Workflow\sandbox\aa\node_modules\babel-core\lib\api\r
egister\node.js:216:7)
    at Module.load (module.js:355:32)
TypeError: Cannot read property 'stack' of undefined
    at error (C:\Users\Frontend\AppData\Roaming\nvm\v0.12.5\node_modules\ava\cli.js:50:19)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at Object.<anonymous> (C:\Users\Frontend\AppData\Roaming\nvm\v0.12.5\node_modules\ava\cli.js:206:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by sindresorhus** [comment]
Do you have a local Babel install? If so, what version?

// @twada

**Comment by sindresorhus** [comment]
@TrySound Not a very useful title. Please try harder the next time ;)

**Comment by TrySound** [comment]
@sindresorhus I just don't know what is the problem :))
```
  "devDependencies": {
    "ava": "^0.3.0"
  },
```

and global the same

**Comment by forabi** [comment]
I have the exact same error on Linux, so apparently it does not have anything to do with Windows.
Here is my `devDependencies`:

```json
{
    "ava": "^0.3.0",
    "babel": "^5.8.23",
    "babel-runtime": "^5.8.25"
}
```

My `.babelrc`

```json
{
  "stage": 1,
  "optional": ["es7.classProperties", "es7.comprehensions"]
}
```

**Comment by TrySound** [comment]
@sindresorhus I use npm3. Maybe babel5 doesn't work on it?

**Comment by forabi** [comment]
@TrySound Well, I thought that was the cause, so I switched to node 0.12 and npm 2, but the issue is still present. So it is not that either.

**Comment by uiureo** [comment]
This might be because `babel-plugin-espower` does not use a local babel.

https://github.com/sindresorhus/ava/blob/1d5ef4c5f6fcb70f9e90e584dfd08865db1e93b4/lib/babel.js#L12

```js
	plugins: [
		createEspowerPlugin(require('babel-core'), {
			patterns: require('./enhance-assert').PATTERNS
		})
	]
};
```

This should be a mistake. I'll create a PR if I can reproduce it.

**Comment by uiureo** [comment]
Reproduced in npm 2.14.2.

package.json
```js
  "devDependencies": {
    "ava": "^0.3.0",
    "babel": "5.8.21",
    "babel-core": "5.8.21"
  }
```

test.js
```js
import test from 'ava';

test((t) => {
  t.pass();
  t.end();
});
```

```
❯ node_modules/.bin/ava 

/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/ava/node_modules/babel-core/lib/transformation/plugin.js:121
      throw new TypeError(messages.get("pluginNotFile", this.key));
      ^

TypeError: Plugin "babel-plugin-espower" is resolving to a different Babel version than what is performing the transformation.
    at Plugin.buildPass (/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/ava/node_modules/babel-core/lib/transformation/plugin.js:121:13)
    at PluginManager.add (/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/babel-core/lib/transformation/file/plugin-manager.js:216:55)
    at File.buildTransformers (/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.transformFileSync (/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/babel-core/lib/api/node.js:133:37)
    at compile (/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/babel-core/lib/api/register/node.js:132:20)
    at normalLoader (/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
TypeError: Cannot read property 'stack' of undefined
    at error (/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/ava/cli.js:50:19)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
From previous event:
    at Object.<anonymous> (/Users/zat/Code/Sandbox/babel-resolve-test/node_modules/ava/cli.js:206:34)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by twada** [comment]
@sindresorhus I'm so sorry that I missed your ping.

@uiureo 

>  I'll create a PR if I can reproduce it.

Thanks a lot!

**Comment by uiureo** [comment]
@TrySound @forabi The patch has been merged into master. Could you try it?

**Comment by TrySound** [comment]
@uiureo Seems like it works. Great!  @sindresorhus Need to make hot patch. When you can release?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ava/milestones/0.4.0

**Comment by TrySound** [comment]
Okay. Thanks.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ava/releases/tag/v0.4.0

**Comment by TrySound** [comment]
@sindresorhus Thanks
