### ISSUE TITLE
Invalid regular expression error when running from the CLI on Windows

### ISSUE THREAD

**Issue by TrySound** [sindresorhus/ava#164]
```
D:\_host\github\postcss-inline-svg>ava

D:\_station\nvm\v0.12.7\node_modules\ava\cli.js:70
                .replace(new RegExp(path.sep, 'g'), separator);
                         ^
SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (native)
    at prefixTitle (D:\_station\nvm\v0.12.7\node_modules\ava\cli.js:70:12)
    at ChildProcess.test (D:\_station\nvm\v0.12.7\node_modules\ava\cli.js:89:12)
    at ChildProcess.emit (events.js:107:17)
    at ChildProcess.<anonymous> (D:\_station\nvm\v0.12.7\node_modules\ava\lib\fork.js:47:6)
    at ChildProcess.emit (events.js:110:17)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
```

Structure
```
test:
- svg/*.svg
- apply-data.js
- ast2data.js
- index.js
```

**Comment by sindresorhus** [comment]
Never tested AVA on Windows, but we're in the process of setting up automated Windows testing.

Looks like we'll need to escape the `path.sep`.

**Comment by sindresorhus** [comment]
// @vdemedes

**Comment by TrySound** [comment]
@sindresorhus It's weird caz it worked yesterday

**Comment by vdemedes** [comment]
@TrySound what versions on node were you using?

**Comment by TrySound** [comment]
@vdemedes 
```
D:\_station\nvm\v0.12.7\node_modules\ava\cli.js:70
```

**Comment by vdemedes** [comment]
@TrySound and yesterday...?

**Comment by TrySound** [comment]
@vdemedes Yas ) My pr fix the problem. But something wrong in node5

**Comment by TrySound** [comment]
@sindresorhus Thanks )
