### ISSUE TITLE
Better error when launched without AVA cli

### ISSUE THREAD

**Issue by timoxley** [sindresorhus/ava#179]
Perhaps throw a more explicit error because at the moment it appears to crash and complain about lack of `process.send`:

```
> node test/index.js
Warning: a promise was rejected with a non-error: [object Undefined]
    at /Users/timoxley/Projects/tests/node_modules/ava/lib/runner.js:163:20
From previous event:
    at Runner.run (/Users/timoxley/Projects/tests/node_modules/ava/lib/runner.js:161:4)
    at Immediate._onImmediate (/Users/timoxley/Projects/tests/node_modules/ava/index.js:53:9)
    at processImmediate [as _immediateCallback] (timers.js:374:17)

Unhandled rejection TypeError: process.send is not a function
    at exit (/Users/timoxley/Projects/tests/node_modules/ava/index.js:42:10)
From previous event:
    at Immediate._onImmediate (/Users/timoxley/Projects/tests/node_modules/ava/index.js:53:15)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

Related #97

**Comment by sindresorhus** [comment]
Agreed. I've already seen this, but forgot to open an issue.
