### ISSUE TITLE
Assertion output regression

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#372]
In master (https://github.com/sindresorhus/ava/commit/945dbea40a6a500a24d54ebcc7e10dcd75647fc7), there's no longer any `power-assert` output.

```js
import test from 'ava';

test(t => {
	t.ok(false);
});
```

```
  1 failed

  1. [anonymous]
  AssertionError: false == true
    at Test.fn (/Users/sindresorhus/dev/md5-hex/test.js:4:4)
```

**Comment by ben-eb** [comment]
Found this whilst writing a failing spec for a module I'm working on; gives this stack trace:

```
  1 passed  1 failed

  1. should return the smallest colour
  AssertionError: should convert percentage based rgba values (5)
    at Decorator.concreteAssert (/Users/beneb/projects/colormin/node_modules/empower-core/lib/decorator.js:95:20)
    at Object.decoratedAssert [as same] (/Users/beneb/projects/colormin/node_modules/empower-core/lib/decorate.js:48:30)
    at Test.fn (/Users/beneb/projects/colormin/dist/__tests__/index.js:43:7)
    at tryCatcher (/Users/beneb/projects/colormin/node_modules/bluebird/js/release/util.js:11:23)
    at Object.gotValue (/Users/beneb/projects/colormin/node_modules/bluebird/js/release/reduce.js:145:18)
    at Object.gotAccum (/Users/beneb/projects/colormin/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/Users/beneb/projects/colormin/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/beneb/projects/colormin/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/Users/beneb/projects/colormin/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromiseCtx (/Users/beneb/projects/colormin/node_modules/bluebird/js/release/promise.js:583:10)
    at Async._drainQueue (/Users/beneb/projects/colormin/node_modules/bluebird/js/release/async.js:130:12)
    at Async._drainQueues (/Users/beneb/projects/colormin/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/beneb/projects/colormin/node_modules/bluebird/js/release/async.js:16:14)
```

Test is simply:

```js
import test from 'ava';
import min from '..';

test('should return the smallest colour', t => {
  t.same(min('rgba(100%,64.7%,0%,.5)'), 'invalid', 'should convert percentage based rgba values (5)');
});
```

**Comment by vdemedes** [comment]
Ok, turns out it's not a bug. It is simply a mini reporter, which does not display error messages. Mini reporter displays only stacks (`err.stack`).

**Comment by vdemedes** [comment]
No, it is a bug at the same time. The above is also valid, but the cause is different. This regression was introduced with the appearance of API.

**Comment by vdemedes** [comment]
Nope, it is not a bug, it is lack of API documentation actually. It also related to #365. Mini reporter was displaying errors at the end of output using `api.tests` property, but it should've used `api.errors` property. Messages in `errors` are enhanced, unlike in `tests`.
