### ISSUE TITLE
t.throws() not catching throw statements

### ISSUE THREAD

**Issue by radiovisual** [sindresorhus/ava#383]
Unless I am overlooking something super simple, It seems that `t.throws()` is favoring rejected promises over `throw` statements.  I have setup a small test in order to demonstrate this behavior. In the code below you will find a module with two functions, one that returns a rejected promise, and another that throws an error. You will see how the test to catch the throw (via the rejected promise) passes, but the test to catch the throw via `throw new Error` does not pass. 

**Consider this very simple `test.js` file:**

```js
import test from 'ava';
import fn from './';

test('AVA should catch my throw statement', t => {
	t.throws(fn.withThrow());
});

test('AVA should catch throw via rejected promise', async t => {
	await t.throws(fn.withPromise());
});
```

**And my equally simple index.js file:**

```js
module.exports.withThrow = function () {
	throw new Error('Error was thrown.');
};

module.exports.withPromise = function () {
	return Promise.reject('Rejected promise');
};
```

And finally, the result of running the tests:

![ava-output](https://cloud.githubusercontent.com/assets/5614571/12024383/56c13834-ad9b-11e5-9142-5bb250f56f2d.png)

<pre>
✖ AVA should catch my throw statement Error was thrown.
✔ AVA should catch throw via rejected promise

  1 test failed

  1. AVA should catch my throw statement
  Error: Error was thrown.
    at Object.module.exports.withThrow (/Users/michael/gitprojects/hash-to-regex/index.js:4:8)
    at Test.fn (/Users/michael/gitprojects/hash-to-regex/test.js:5:14)
    at tryCatcher (/Users/michael/gitprojects/hash-to-regex/node_modules/bluebird/js/release/util.js:11:23)
    at Object.gotValue (/Users/michael/gitprojects/hash-to-regex/node_modules/bluebird/js/release/reduce.js:145:18)
    at Object.gotAccum (/Users/michael/gitprojects/hash-to-regex/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/Users/michael/gitprojects/hash-to-regex/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/michael/gitprojects/hash-to-regex/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/Users/michael/gitprojects/hash-to-regex/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromiseCtx (/Users/michael/gitprojects/hash-to-regex/node_modules/bluebird/js/release/promise.js:583:10)
    at Async._drainQueue (/Users/michael/gitprojects/hash-to-regex/node_modules/bluebird/js/release/async.js:130:12)
    at Async._drainQueues (/Users/michael/gitprojects/hash-to-regex/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/michael/gitprojects/hash-to-regex/node_modules/bluebird/js/release/async.js:16:14)
</pre>

Both tests should pass, correct? Am I missing something, or is `t.throws()` favoring rejected promises over throw statements?

**Comment by radiovisual** [comment]
I am using AVA 0.8.0.

**Comment by vdemedes** [comment]
`fn.withThrow()` throws before even getting to `t.throws`: `t.throws(fn.withThrow())`. So `t.throws()` is not executed at all. The correct code would be:

```js
t.throws(function () {
  fn.withThrow();
});
```

or:

```js
t.throws(fn.withThrow);
```

**Comment by radiovisual** [comment]
Ah yes. @vdemedes  You're right. I figured I was staring directly at the problem. Thanks.
