### ISSUE TITLE
Cannot read property 'start' of undefined (related to babel@6.5.0/1 update)

### ISSUE THREAD

**Issue by MoOx** [sindresorhus/ava#538]
Here is my file which can't even be "started" since recent a babel update (6.5.1?)

You will not need anything but my file itself to reproduce (I guess the parsing fail somewhere)...
Looks like it's the same kind of issue that just popup here https://github.com/istarkov/babel-plugin-webpack-loaders/issues/15

```js
import test from "ava"; import "babel-core/register"

import feed from "../feed"

test("statinamic/lib/md-collection-loader feed helper", (t) => {

  t.is(
    feed({
      feedOptions: {
        title: "test",
        site_url: "http://statinamic.test/",
      },
      destination: "feed.xml",
      collection: [
        {
          title: "One",
          date: "2015-01-01",
          description: "<strong>One</strong>",
          __filename: "page/one.md",
          __url: "/page/one/",
        },
        {
          title: "Two",
          date: "2015-12-31",
          description: "<strong>Two</strong>",
          __filename: "page/two.md",
          __url: "/page/two/",
        },
      ],

      // for testing
      xmlOptions: { indent: "  " },
    }),

    /* eslint-disable max-len */
    `<?xml version="1.0" encoding="UTF-8"?><rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title><![CDATA[test]]></title>
    <description><![CDATA[test]]></description>
    <link>http://statinamic.test/</link>
    <generator>RSS for Node</generator>
    <lastBuildDate>${ (new Date()).toUTCString() }</lastBuildDate>
    <atom:link href="http://statinamic.test/feed.xml" rel="self" type="application/rss+xml"/>
    <item>
      <title><![CDATA[One]]></title>
      <description><![CDATA[<strong>One</strong>]]></description>
      <link>http://statinamic.test/page/one/</link>
      <guid isPermaLink="true">http://statinamic.test/page/one/</guid>
      <pubDate>Thu, 01 Jan 2015 00:00:00 GMT</pubDate>
    </item>
    <item>
      <title><![CDATA[Two]]></title>
      <description><![CDATA[<strong>Two</strong>]]></description>
      <link>http://statinamic.test/page/two/</link>
      <guid isPermaLink="true">http://statinamic.test/page/two/</guid>
      <pubDate>Thu, 31 Dec 2015 00:00:00 GMT</pubDate>
    </item>
  </channel>
</rss>`,
    "should generate a feed from a collection"
  )
})
```

Here a minimal test case

```console
~/Sync/Development
❯ mkd ava-fail

~/Sync/Development/ava-fail
❯ node --version
v5.5.0

~/Sync/Development/ava-fail
❯ npm --version
3.7.1

~/Sync/Development/ava-fail
❯ npm i ava@^0.11.0

~/Sync/Development/ava-fail 3m 43s
❯ pbpaste > fail.js

~/Sync/Development/ava-fail
❯ ava fail.js

TypeError: /Users/MoOx/Sync/Development/ava-fail/fail.js: Cannot read property 'start' of undefined
    at /Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/whitespace.js:29:19
    at Whitespace._findToken (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/whitespace.js:99:30)
    at Whitespace.getNewlinesBefore (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/whitespace.js:28:22)
    at CodeGenerator.printComment (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/printer.js:321:34)
    at CodeGenerator.printComments (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/printer.js:377:12)
    at CodeGenerator.printLeadingComments (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/printer.js:231:10)
    at CodeGenerator.print (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/printer.js:81:10)
    at CodeGenerator.printJoin (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/printer.js:193:12)
    at CodeGenerator.printList (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/printer.js:258:17)
    at CodeGenerator.ObjectExpression (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/generators/types.js:48:10)
    at CodeGenerator._print (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/printer.js:155:17)
    at CodeGenerator.print (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/printer.js:91:10)
    at CodeGenerator.printJoin (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/printer.js:193:12)
    at CodeGenerator.printList (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/printer.js:258:17)
    at CodeGenerator.CallExpression (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/generators/expressions.js:142:8)
    at CodeGenerator._print (/Users/MoOx/Sync/Development/ava-fail/node_modules/babel-generator/lib/printer.js:155:17)
From previous event:
    at Api.run (/Users/MoOx/Sync/Development/ava-fail/node_modules/ava/api.js:148:4)
    at Object.<anonymous> (/Users/MoOx/Sync/Development/ava-fail/node_modules/ava/cli.js:115:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

## Workaround

```js
import test from "ava"; import "babel-core/register"

import feed from "../feed"

test("statinamic/lib/md-collection-loader feed helper", (t) => {

  const feedXML = feed({
    feedOptions: {
      title: "test",
      site_url: "http://statinamic.test/",
    },
    destination: "feed.xml",
    collection: [
      {
        title: "One",
        date: "2015-01-01",
        description: "<strong>One</strong>",
        __filename: "page/one.md",
        __url: "/page/one/",
      },
      {
        title: "Two",
        date: "2015-12-31",
        description: "<strong>Two</strong>",
        __filename: "page/two.md",
        __url: "/page/two/",
      },
    ],

    // for testing
    xmlOptions: { indent: "  " },
  })

  /* eslint-disable max-len */
  const feedXMLexpected = `<?xml version="1.0" encoding="UTF-8"?><rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title><![CDATA[test]]></title>
    <description><![CDATA[test]]></description>
    <link>http://statinamic.test/</link>
    <generator>RSS for Node</generator>
    <lastBuildDate>${ (new Date()).toUTCString() }</lastBuildDate>
    <atom:link href="http://statinamic.test/feed.xml" rel="self" type="application/rss+xml"/>
    <item>
      <title><![CDATA[One]]></title>
      <description><![CDATA[<strong>One</strong>]]></description>
      <link>http://statinamic.test/page/one/</link>
      <guid isPermaLink="true">http://statinamic.test/page/one/</guid>
      <pubDate>Thu, 01 Jan 2015 00:00:00 GMT</pubDate>
    </item>
    <item>
      <title><![CDATA[Two]]></title>
      <description><![CDATA[<strong>Two</strong>]]></description>
      <link>http://statinamic.test/page/two/</link>
      <guid isPermaLink="true">http://statinamic.test/page/two/</guid>
      <pubDate>Thu, 31 Dec 2015 00:00:00 GMT</pubDate>
    </item>
  </channel>
</rss>`

  t.is(
    feedXML,
    feedXMLexpected,
    "should generate a feed from a collection"
  )
})
```

**Comment by MoOx** [comment]
FYI, I am facing this issue on multiple (all?) projects (eg: https://travis-ci.org/postcss/postcss-import/jobs/108972544#L631) poke @hzoo

**Comment by hzoo** [comment]
Looking..

Also a simplier snippet from what you had that fails

```js
import test from "ava";

test("a", t => {
  t.is(
    {
      // for testing
    },
    1
  );
});
```

If the comment is removed that error is gone.

**Comment by mastilver** [comment]
@hzoo I came to the same conclusion

"fix" for postcss-import: https://github.com/postcss/postcss-import/pull/172

**Comment by hzoo** [comment]
And then fixing that by reverting that PR only lead me to find an acorn error?

```bash
hzhu/dev/test/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:945
  throw err;
  ^

SyntaxError: Unexpected token (1:17)
    at Parser.pp.raise (/Users/hzhu/dev/test/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:943:13)
    at Parser.pp.unexpected (/Users/hzhu/dev/test/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:1503:8)
    at Parser.pp.parseIdent (/Users/hzhu/dev/test/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:670:10)
    at Parser.parseIdent (/Users/hzhu/dev/test/node_modules/acorn-es7-plugin/acorn-es7-plugin.js:93:19)
    at Parser.pp.parsePropertyName (/Users/hzhu/dev/test/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:554:127)
```
Not sure about this

**Comment by sindresorhus** [comment]
> hzhu/dev/test/node_modules/**power-assert-formatter**/node_modules/acorn/dist/acorn.js:945

@twada Any chance power-assert has something to do with this issue?

**Comment by gzzhanghao** [comment]
@hzoo acorn.input becomes `t.is({ // comment }, 1)` in your case. Forcing a newline in concise mode at https://github.com/babel/babel/blob/master/packages/babel-generator/src/printer.js#L300 should help.

**Comment by BarryThePenguin** [comment]
Related? sindresorhus/xo#79

**Comment by twada** [comment]
@sindresorhus Understood. I'll fix babel-plugin-espower ASAP.
Thanks @hzoo @gzzhanghao !

**Comment by twada** [comment]
Just released [babel-plugin-espower 2.1.2](https://github.com/power-assert-js/babel-plugin-espower/blob/master/CHANGELOG.md#212-2016-02-14) to fix the problem. Thank you for reporting and suggestions.

**Comment by twada** [comment]
@MoOx would you reinstall ava and try again?

**Comment by sindresorhus** [comment]
@BarryThePenguin Yup.

@twada Thanks for the quick response. That did it for me.

**Comment by MoOx** [comment]
Thanks guys! This is now ok.
